### ISSUE TITLE
Chrome Synced Tabs prevent using this extension

### ISSUE THREAD

**Issue by konstantin83** [harshayburadkar/clut-chrome-extension#17]
Hey! First of all thanks for your extension!
It stoped working normally after I started using synced tabs in recent Chrome update.
Maybe you could fix this?

**Comment by konstantin83** [comment]
@harshayburadkar, Please respond. I literally can't use chrome without your extension anymore ))

**Comment by AnnisVeryGoodCode** [comment]
It's also stopped working for me with the default shortcut. I also recently started using synced tab groups but did not explicitly confirm that the issue is related to that.

Changing the shortcut to something else worked for me (but after years of ALT-W, this is tough...).

Edit: Actually, changing the shortcut only briefly fixed the issue. After viewing a tab in a tab group, it only works occasionally (but doesn't most of the time).

**Comment by konstantin83** [comment]
@AnnisVeryGoodCode it's pretty easy to confirm the dependence of synced tabs — just hide all of them and alt+w will work as usual without poltergeist behaviour.

Alse please tell me how did you manage to change the keyboard shortcut in extension?

**Comment by AnnisVeryGoodCode** [comment]
Right, it's actually not the presence of the functionality in the new Chrome version, but simply using it that breaks CLUT. 
If you turn off sync for your open tab groups (but keep the groups), it also goes back to working, in case that's an option for you. You can also keep already-saved-but-hidden tab groups in your bookmarks bar.

I'll resolve to that for now since CLUT is more important.

To change the shortcut: 3 dots at the top right of the window > Extensions > Manage Extensions > Keyboard Shortcuts (2nd item in the left menu bar) > Scroll to CLUT > Adjust "Quick switch" shortcut.

**Comment by konstantin83** [comment]
Thank you! But you're definitely right — after lots of years you simply have a muscle memory for Alt+W and don't want anything to change ))
But author still doesn't reply, so maybe the extension is abandoned.

**Comment by harshayburadkar** [comment]
@konstantin83 @AnnisVeryGoodCode
I tested tab groups and synced tabs and both of them still work for me.


Please note that the extension works with the last "used" tabs. The definition of the term "used" here is that you should have visited the tab in Chrome. If you did a right click on a link and opened it in a new tab without actually navigating to that new tab it will not be considered as a "used" tab for the purpose of the extension. 
Similarly for synced tabs or saved tab groups - if they get opened by Chrome from a last session but unless you have visited them since launching Chrome they will not be remembered by extension as a recently used tab because technically you have not visited (used) that tab yet.

 Just manually use the tabs for the first time and the extension will do it's job to remember the used (visited) tab order. This behavior is the same from the initial version of the extension.


Let's try to drill down on this if needed. @konstantin83 if you still face the issues after the above clarifications, please share the steps that I can take to see the issue on my side as well.

**Comment by konstantin83** [comment]
@harshayburadkar Thank you for you reply. 
Of course, I understand hot CLUT works, since I've been using it thousands time a day for many years.

> Let's try to drill down on this if needed. @konstantin83 if you still face the issues after the above clarifications, please share the steps that I can take to see the issue on my side as well.

It's very simple. CLUT works fine when there are only normal tabs in Chrome window.
BUT. When you use Tabs Groups from the latest Chrome update (first block here https://www.google.com/intl/en_us/chrome/whats-new/m122/) with the "Save group" switched On, then all CLUT tabs cycle breaks when you click on any tab from this group.
And then you should click at least three tabs outside the group for CLUT to start working again normally.

Please try this out.
I can make a video of the process. But it is so simple, that probably it would not be necessary.

**Comment by konstantin83** [comment]
Friends! It's all working now as it was before!
I think it's the Chrome update that fixed the bug.
Hooray! God bless the CLUT!
