### ISSUE TITLE
Is There a Way to Verify that This Script is Safe and Clean?

### ISSUE THREAD

**Issue by CerebralFreeze** [harshayburadkar/clut-chrome-extension#7]
I'm not experienced enough with computers to look at the search code and see if there is anything wrong with it.  I also don't want to make any false accusations.  I just ran my antivirus program and it labeled Clut as a danger and deleted it.

This really scares me since I downloaded the antivirus program because things were going wrong with my computer.  I'm worried that Clut was the cause.

**Comment by harshayburadkar** [comment]
It is absolutely clean - use it without a worry! 

This extension has been used majorly by technical people and is their extension of choice for many as compared to the alternatives.

**Comment by harshayburadkar** [comment]
If you wish to you can get any technical friend of yours to read the code from the installed browser extension too.

I never have received this type of query but I think your concern is legitimate. There was one person who asked why is there Google Analytics included - but that is just to know how many people actively use it as opposed to just install and forget it. It helps me to know if the extension is really helping and to prioritize any new changes. It only displays that 10,000 people used it in the last week without any details of anyone's browsing history or anything of that sort.

**Comment by CerebralFreeze** [comment]
Harshayburadkar,

There is no way for me to tell if you are telling the truth.  Literally, given the evidence, there is no possible way!  But, I believe you.  You sound sincere.  Let me thank you on behalf of the 9,999 other people who use it, thank you for making such a useful extension.  It's truly increases my productivity and you are a godsend.

What makes it even better is your prompt response!  I'm curious.  Is there any way that you benefit monetarily from this?  Why do the people like you on Github, work on the code as hard as they do?  Is it purely from knowing that they made a quality-program that a lot of people love?  Can they convert the program into a for-profit code later?  Or, perhaps do they use it as a project that they can show to prospective employers, demonstrating their competence?

Is there a way to donate to you for your time and effort?

Thank you again for a small program that makes a substantial impact to a lot of people!

**Comment by harshayburadkar** [comment]
Thank you and I am happy it helps you.

There is certain happiness you get when you are able to impact the lives of
so many people in a positive way. The power of the internet in combination
with the skill to create things on it makes it easier for me. I always
liked having some 'real estate' on the internet even if it is a 'not for
profit'.
I do not get anything from this project. There isn't a way of donation
setup because I would need to figure out legalities with a CA. I am working
hard on a project called TestRobo(testrobo.io) currently - I suppose you
wouldn't have an angel investor friend itching to invest money - do you? 😋

But I would like to suggest being vigilant with extensions.
Continuously keep deactivating whichever ones you don't use. There are
companies that will offer money asking to transfer ownership of
the extension. I am sure they are looking to extract data from the users by
injecting additional code via an extension. But it's all subjective - most
likely all of our PII is already floating on the dark web for few dollars
anyway. Unfortunately, that's the truth!


Regards,
Harshay

P.S. Just recently I have also created an app -  https://whyno.space This
is free too. Core features all working but polishing of UI etc. are not
there due to lack of time. About WhyNoSpace <https://whyno.space/about>
